### PR TITLE
fix: Remove `GroupInfo`s `tls_codec::Deserialize` implementation. 

### LINKED ISSUE #1181: `GroupInfo` can be deserialized, thus skipping the verification step

### PR DESCRIPTION
**Pull request by duesee**
This implementation should not exist because it can be used to bypass signature verification.

This closes #1181.

### CODE REVIEW

File: openmls/src/messages/mod.rs [hunk 1]
```diff
@@ -241,6 +241,7 @@ impl Signable for GroupInfoTBS {
 /// } GroupInfo;
 /// ```
 #[derive(Debug, PartialEq, Clone)]
+#[cfg_attr(feature = "test-utils", derive(TlsDeserialize))]
```
Comment (duesee) [inline openmls/src/messages/mod.rs:244]: This is needed because `MlsMessageOutBody` derives `TlsDeserialize` under the same conditions and uses `GroupInfo`.

File: openmls/src/messages/mod.rs [hunk 2]
```diff
@@ -262,11 +263,6 @@ impl GroupInfo {
         &self.payload.confirmation_tag
     }
 
-    /// Returns the signer.
```
Comment (duesee) [inline openmls/src/messages/mod.rs:265]: This is not used anymore in `pub(crate)`. If we want to keep it, we should define a public API.

File: openmls/src/messages/tests/test_welcome.rs [hunk 3]
```diff
@@ -162,26 +163,24 @@ fn test_welcome_ciphersuite_mismatch(
     let group_info_bytes = welcome_key
         .aead_open(backend, welcome.encrypted_group_info(), &[], &welcome_nonce)
         .expect("Could not decrypt GroupInfo.");
-    let mut group_info = GroupInfo::tls_deserialize(&mut group_info_bytes.as_slice())
-        .expect("Could not deserialize GroupInfo.");
```
Comment (duesee) [inline openmls/src/messages/tests/test_welcome.rs:166]: Expects like this can easily get out-of-sync and the `expect` doesn't really add information here. Thus, I used `unwrap` instead.

**Review by kkohbrok — APPROVED** [review]
Looks good to me, thanks!

File: openmls/src/messages/tests/test_welcome.rs [hunk 4]
```diff
@@ -162,26 +163,24 @@ fn test_welcome_ciphersuite_mismatch(
...
 
-    let encrypted_group_info = welcome_key
-        .aead_seal(backend, &group_info_bytes, &[], &welcome_nonce)
-        .expect("Could not encrypt GroupInfo.");
+    let encrypted_verifiable_group_info = welcome_key
+        .aead_seal(backend, &verifiable_group_info_bytes, &[], &welcome_nonce)
+        .unwrap();
 
-    welcome.encrypted_group_info = encrypted_group_info.into();
+    welcome.encrypted_group_info = encrypted_verifiable_group_info.into();
```
Comment (duesee) [inline openmls/src/messages/tests/test_welcome.rs:183]: Here, we "coerce" a previously *unverified* `group info (seemingly) into a group info (`encrypted_group_info` vs `unverified_encrypted_group_info`). I'm not sure if this is something we should worry about right now.

Comment (kkohbrok) [reply openmls/src/messages/tests/test_welcome.rs:183]: What we want would be something like: Encryption only for `GroupInfo`, decryption should always yield a `UnverifiedGroupInfo`. For tests, I think coercion is okay.
