### PR TITLE
Annotate and fix missing validation checks, including ones we hadn't catalogued before

### LINKED ISSUE #800: Public tree validation: validate unmerged leaves
Unmerged leaves should be checked according to (at least) the following criteria:

 - [ ] the should be in the subtree of the node
 - [ ] they should not be blank
 - [ ] #1120 (they should be unique & ordered)

### LINKED ISSUE #803: External Commit validation: unused variants
The variants `NoPath`, `UnknownMemberRemoval`, and `MultipleRemoveProposals` in `ExternalCommitValidationError` seem useful but are not used.

### LINKED ISSUE #807: [Meta] Tree Validation
This ticket tracks other tickets related to the validation of trees that the client receives. 

- [ ] create list of tree validation steps
- [ ] #800 
- [ ] parent hash validation (documentation and testing)
- [ ] node validation (only keypackages in leaves, only parent nodes in non-leaves)

### LINKED ISSUE #1536: Protocol version validation
The protocol version for incoming messages is not fully verified currently.

### PR DESCRIPTION
**Pull request by keks**
This adds validation for external commits and welcomes, and protocol versions.

This is mostly annotation, but the welcome message validation checks were actually missing.

Fixes #800
Fixes #803
Fixes #807
Fixes #1536

### CODE REVIEW

File: openmls/src/binary_tree/array_representation/tree.rs [hunk 1]
```diff
@@ -215,7 +215,6 @@ impl<L: Clone + Debug + Default, P: Clone + Debug + Default> ABinaryTree<L, P> {
     }
 }
 
-#[cfg(test)]
```
Comment (kkohbrok) [inline openmls/src/binary_tree/array_representation/tree.rs:218]: Do you want to merge this into the impl block above this?

File: openmls/src/group/public_group/mod.rs [hunk 2]
```diff
@@ -141,6 +147,49 @@ impl PublicGroup {
             .full_leaves()
             .try_for_each(|leaf_node| leaf_node.validate_locally())?;
 
+        // For each non-empty parent node and each entry in the node's unmerged_leaves field:
+        treesync
```
Comment (kkohbrok) [inline openmls/src/group/public_group/mod.rs:151]: Shouldn't this whole block be part of `into_verified` that's called above? In any case it might be good to make it its own function.

File: openmls/src/treesync/mod.rs [hunk 3]
```diff
@@ -482,6 +488,31 @@ impl TreeSync {
...
+                    .parents()
+                    .flat_map(|(_, node)| node.node().as_ref().map(ParentNode::encryption_key)),
+            )
+            .try_fold(HashSet::new(), |mut leaves, key| {
+                if !leaves.insert(key) {
+                    return Err(RatchetTreeError::DuplicateEncryptionKey);
+                }
+
+                Ok(leaves)
+            })?;
```
Comment (kkohbrok) [inline openmls/src/treesync/mod.rs:514]: This probably isn't that much of a performance concern (and we can do it in a separate PR), but between the different validation steps we iterate over the whole tree multiple times. I wonder if we can't streamline that somehow.

**Review by kkohbrok — COMMENTED** [review]
Thanks, this fills a few important gaps! Just a few comments.

File: openmls/src/group/public_group/mod.rs (hunk 2 above)
Comment (kkohbrok) [reply openmls/src/group/public_group/mod.rs:151]: Fair enough. Let's leave it like this for now.

File: openmls/src/treesync/mod.rs (hunk 3 above)
Comment (keks) [reply openmls/src/treesync/mod.rs]: I pasted the body of the loop that iterated over both leaves and parents into each of the two loops in that I do in the other file. There might be more to gain somewhere else, but there was nothing that I saw that would be obvious and wouldn't clutter the code.

Comment (kkohbrok) [reply openmls/src/treesync/mod.rs]: Thanks!

**Review by kkohbrok — APPROVED** [review]
Thanks!
