### PR TITLE
Minor fixes to message formats and mlspp test vectors

### LINKED ISSUE #373: [MLS Spec change] message format changes (#466)
**Description of the changes**
PR #466 to the MLS spec contains some changes to the MLS message format. Relevant for OpenMLS are:
* `confirmation_tag` in MLSPlaintextCommitAuthData is now `optional`
* `extension_data` in `Extension` is now up to `2^32-1` long

**Link to the exact changes**
https://github.com/mlswg/mls-protocol/pull/466/

### PR DESCRIPTION
**Pull request by kkohbrok**
This PR brings over a few changes from the interop branch. In particular, it adds mlspp test vectors, which get checked along with OpenMLS' own test vectors and adds a missing chunk of encryption test vector checking. Additionally, it fixes #373. It's essentially an updated version of #379 by @franziskuskiefer plus extending the size of the `extension_data` vector as per spec change.

### CODE REVIEW

File: src/group/mls_group/apply_commit.rs [hunk 1]
```diff
@@ -145,11 +145,7 @@ impl MlsGroup {
         key_schedule.add_context(&provisional_group_context)?;
         let provisional_epoch_secrets = key_schedule.epoch_secrets(true)?;
 
-        let mls_plaintext_commit_auth_data =
-            match MlsPlaintextCommitAuthData::try_from(mls_plaintext) {
-                Ok(mpcad) => mpcad,
-                Err(_) => return Err(ApplyCommitError::ConfirmationTagMissing),
-            };
+        let mls_plaintext_commit_auth_data = MlsPlaintextCommitAuthData::from(mls_plaintext);
```
Comment (franziskuskiefer) [inline src/group/mls_group/apply_commit.rs:148]: I think this might have been why I kept it a `try_from`. We probably still want to fail here if the tag is missing in the `mls_plaintext` even if we can now just put the `None` in the `MlsPlaintextCommitAuthData` as well.

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
lgtm except that I think I'd keep the `try_from` to catch missing tags. Maybe we should add a test case for this as well to make sure we fail properly. I don't think we excercise this right now and I'm not sure we handle it right.

File: src/group/mls_group/apply_commit.rs (hunk 1 above)
Comment (kkohbrok) [reply src/group/mls_group/apply_commit.rs:148]: Good catch! We should definitely fail when there's no ConfirmationTag. I'll revert it to `try_from` and add a failure condition for when no tag is present. Also, a test, of course.

**Review by franziskuskiefer — APPROVED** [review]
Yay, more tests. Thanks!

File: src/group/tests/kat_transcripts.rs [hunk 2]
```diff
@@ -190,13 +203,23 @@ pub fn run_test_vector(test_vector: TranscriptTestVector) -> Result<(), Transcri
         return Err(TranscriptTestVectorError::MembershipTagVerificationError);
     }
 
-    let my_confirmation_tag = confirmation_key.tag(&confirmed_transcript_hash_before);
+    //let my_confirmation_tag = confirmation_key.tag(&confirmed_transcript_hash_before);
+    let confirmed_transcript_hash_after =
+        hex_to_bytes(&test_vector.confirmed_transcript_hash_after);
```
Comment (raphaelrobert) [inline src/group/tests/kat_transcripts.rs:208]: This seems to trigger a clippy warning above (L181), because `confirmed_transcript_hash_before` doesn't need to be cloned anymore.

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
Thanks, LGTM! (just one nit)

**Review by raphaelrobert — APPROVED** [review]
