### PR TITLE
Fix remover bug

### LINKED ISSUE #329: [Bug] Wrong remover in callback function of ManagedGroup
**Describe the bug**
`ManagedGroup` incorrectly reports the sender of a Commit as the remover, when proposals by reference are used.

**To Reproduce**
 - Alice issues a `RemoveProposal` to remove Bob
 - Charlie commits that proposal

**Expected behavior**
The callback function should report "Alice removed Bob"

**Actual behavior**
The callback function reports "Charlie removed Bob"

**Screenshots or debug log**
N/A

**Platform (please complete the following information):**
all

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by raphaelrobert**
This PR fixes #329 by passing the correct sender to the event dispatcher and additionally fixes the wrong order of leaver and remover in the callback.

A small step in code change, a huge leap in testing.

### CODE REVIEW

**Review by kkohbrok — DISMISSED** [review]
Looks good to me! Thanks for the fix!

File: src/group/managed_group/mod.rs [hunk 1]
```diff
@@ -898,7 +898,7 @@ impl<'a> ManagedGroup<'a> {
                     if let Some(queued_proposal) = pending_proposals_queue.get(proposal_reference) {
                         self.send_proposal_event(
                             queued_proposal.proposal(),
-                            sender,
+                            &queued_proposal.sender().to_leaf_index(),
```
Comment (franziskuskiefer) [inline src/group/managed_group/mod.rs:901]: This shouldn't borrow. But feel free to do in a follow up.

**Review by franziskuskiefer — APPROVED** [review]
lgtm with one nit.
We definitely need more tests.

File: src/group/managed_group/mod.rs (hunk 1 above)
Comment (raphaelrobert) [reply src/group/managed_group/mod.rs:901]: Agreed, it's a bit inconsistent. I can make `.to_leaf_index()` return a `&LeafIndex` and that would be my preferred way. This will lead to some more code changes elsewhere. Let me know if you're fine with that.

Alternatively I could just change the function signature of `send_proposal_event()` to accept a `LeafIndex` and copy the value. Less preferred, but also less code changes.

**Comment by raphaelrobert** [comment]
> lgtm with one nit.
> We definitely need more tests.

I filed #332.

File: src/group/managed_group/mod.rs (hunk 1 above)
Comment (franziskuskiefer) [reply src/group/managed_group/mod.rs:901]: Well, `LeafIndex` really is a `u32`, which should be passed by value. If the compiler actually uses a reference here, it's probably more expensive than passing the value. So I'd recommend doing the second option.

**Review by franziskuskiefer — APPROVED** [review]
