### PR TITLE
Fix schedule rustdocs

### LINKED ISSUE #775: schedule rustdocs

### PR DESCRIPTION
**Pull request by raphaelrobert**
Fixes #775.

This PR also re-adjusts the exporting part of the `MlsGroup` API, so that `AuthenticationSecret` and `ResumptionSecret` are aligned.

### CODE REVIEW

File: openmls/src/schedule/mod.rs [hunk 1]
```diff
@@ -152,13 +157,66 @@ mod unit_tests;
...
+// Public
 pub use errors::*;
 
 // Crate
 pub(crate) use message_secrets::*;
 pub(crate) use psk::*;
 
+// Public types
+
+/// A group secret that can be used among members to prove that a member was part of a group.
```
Comment (kkohbrok) [inline openmls/src/schedule/mod.rs:169]:
```suggestion
/// A group secret that can be used among members to prove that a member was part of a group in a given epoch.
```

**Review by kkohbrok — CHANGES_REQUESTED** [review]
Thanks for the PR! From a structural standpoint, wouldn't it make more sense to make the schedule (crate) private and instead re-export the Resumption and Authentication Secret explicitly as part of the `MlsGroup` API? In my mind, the `schedule`, much like `treesync` is more of an MLS-internal component that shouldn't really be visible to the consumer.

**Review by kkohbrok — APPROVED** [review]
Thanks!
