### PR TITLE
Fix group API rustdoc

### LINKED ISSUE #779: Group API rustdoc

### PR DESCRIPTION
**Pull request by raphaelrobert**
Fixes #779.

### CODE REVIEW

File: openmls/src/group/mls_group/config.rs [hunk 1]
```diff
@@ -5,7 +5,8 @@ use crate::tree::sender_ratchet::SenderRatchetConfiguration;
 use lazy_static::lazy_static;
 use serde::{Deserialize, Serialize};
 
-/// Specifies the configuration parameters for a [`MlsGroup`]
+/// Specifies the configuration parameters for a [`MlsGroup`]. Refer to
+/// the user manual for more information about the different configuration values.
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/config.rs:9]: Can you make the "Refer to" a link?

File: openmls/src/group/mls_group/creation.rs [hunk 2]
```diff
@@ -13,7 +13,8 @@ impl MlsGroup {
 
     /// Creates a new group from scratch with only the creator as a member. This
     /// function removes the `KeyPackageBundle` corresponding to the
-    /// `key_package_hash` from the `backend`. Throws an error if no
+    /// `key_package_hash` from the key store. Returns an error
+    /// (`NewGroupError::NoMatchingKeyPackageBundle`) if no
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/creation.rs:17]:
```suggestion
    /// ([`NewGroupError::NoMatchingKeyPackageBundle`]) if no
```

File: openmls/src/group/mls_group/creation.rs [hunk 3]
```diff
@@ -13,7 +13,8 @@ impl MlsGroup {
...
     /// `KeyPackageBundle` can be found.
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/creation.rs:18]:
```suggestion
    /// [`KeyPackageBundle`] can be found.
```

File: openmls/src/group/mls_group/creation.rs [hunk 4]
```diff
@@ -71,7 +72,9 @@ impl MlsGroup {
         Ok(mls_group)
     }
 
-    /// Creates a new group from a `Welcome` message
+    /// Creates a new group from a `Welcome` message. Returns an error
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/creation.rs:75]:
```suggestion
    /// Creates a new group from a [`Welcome`] message. Returns an error
```

File: openmls/src/group/mls_group/creation.rs [hunk 5]
```diff
@@ -71,7 +72,9 @@ impl MlsGroup {
...
+    /// (`WelcomeError::NoMatchingKeyPackageBundle`) if no
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/creation.rs:76]:
```suggestion
    /// ([`WelcomeError::NoMatchingKeyPackageBundle`]) if no
```

File: openmls/src/group/mls_group/creation.rs [hunk 6]
```diff
@@ -71,7 +72,9 @@ impl MlsGroup {
...
+    /// `KeyPackageBundle` can be found.
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/creation.rs:77]:
```suggestion
    /// [`KeyPackageBundle`] can be found.
```

File: openmls/src/group/mls_group/errors.rs [hunk 7]
```diff
@@ -1,14 +1,17 @@
-//! # MLS MlsGroup errors
+//! # MlsGroup errors
 //!
-//! `WelcomeError`, `StageCommitError`, `DecryptionError`, and
-//! `CreateCommitError`.
+//! This module defines the public errors that can be returned from various calls
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/errors.rs:3]: "various calls" is a little vague. Can we list them? Or is it all?

File: openmls/src/group/mls_group/exporting.rs [hunk 8]
```diff
@@ -7,7 +7,11 @@ use super::*;
 impl MlsGroup {
     // === Export secrets ===
 
-    /// Exports a secret from the current epoch
+    /// Exports a secret from the current epoch.
+    /// Returns `ExportSecretError::KeyLengthTooLong` if the requested
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/exporting.rs:11]:
```suggestion
    /// Returns [`ExportSecretError::KeyLengthTooLong`] if the requested
```

File: openmls/src/group/mls_group/exporting.rs [hunk 9]
```diff
@@ -7,7 +7,11 @@ use super::*;
...
+    /// key length is too long.
+    /// Returns `ExportSecretError::GroupStateError(MlsGroupStateError::UseAfterEviction)`
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/exporting.rs:13]:
```suggestion
    /// Returns [`ExportSecretError::GroupStateError(MlsGroupStateError::UseAfterEviction)`](MlsGroupStateError::UseAfterEviction)
```

File: openmls/src/group/mls_group/processing.rs [hunk 10]
```diff
@@ -11,8 +11,8 @@ use tls_codec::Serialize;
 use super::{errors::UnverifiedMessageError, *};
 
 impl MlsGroup {
-    /// This function is used to parse messages from the DS.
-    /// It checks for syntactic errors and makes some semantic checks as well.
+    /// Parses incoming messages from the DS.
+    /// Checks for syntactic errors and makes some semantic checks as well.
     /// If the input is a `MlsCiphertext` message, it will be decrypted.
```
Comment (franziskuskiefer) [inline openmls/src/group/mls_group/processing.rs:16]: If `MlsCiphertext` is not public, the API shouldn't talk about it in this way.

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
Thanks, only a few nits

File: openmls/src/group/mls_group/mod.rs [hunk 11]
```diff
@@ -123,21 +123,21 @@ pub enum MlsGroupState {
     Inactive,
 }
 
-/// A `MlsGroup` represents an CoreGroup with
-/// an easier, high-level API designed to be used in production. The API exposes
+/// A `MlsGroup` represents an MLS group with
+/// an easy, high-level API designed to be used in production. The API exposes
```
Comment (kkohbrok) [inline openmls/src/group/mls_group/mod.rs:127]:
```suggestion
/// a high-level API. The API exposes
```
Since we don't expose `CoreGroup` anymore, there's no need to be specific about where this is meant to be used.

**Review by franziskuskiefer — APPROVED** [review]

**Review by kkohbrok — APPROVED** [review]
Thanks!
