### PR TITLE
Check for last resort in core_group/new_from_welcome

### LINKED ISSUE #1502: [Bug] KeyPackage with LastResortExtension still removed from key store when calling group::MlsGroup::new_from_welcome
First of all, I think the library is an outstanding piece of technology.  Congratulations to all who contributed to the protocol and to this implementation.

Second, I have a proposed bugfix.  Happy to contribute.

**Describe the bug**
A KeyPackage with LastResortExtension is still removed from key store when calling group::MlsGroup::new_from_welcome(...).

**To Reproduce**
With three separate agents alice, bob, charlie with separate OpenMlsRustCrypto:
1. alice creates MlsGroup
2. bob creates MlsGroup
3. charlie creates KeyPackage
4. alice calls add_members(...) with charlie's KeyPackage; produces Commit and Welcome messages
5. charlie calls new_from_welcome(...) with alice's Welcome message
6. bob calls add_members(...) with charlie's KeyPackage; produces Commit and Welcome messages
7. charlie calls new_from_welcome(...) with charlie's Welcome message

**Expected behavior**
new_from_welcome(...) succeeds both times, producing two separate MlsGroup objects

**Actual behavior**
`No matching encryption key was found in the key store.` when making second new_from_welcome(...) call

**Screenshots or debug log**
On alice:
```bash
 DEBUG openmls::group::core_group > Created group GroupId { value: VLBytes { 0x616c696365 } }
 DEBUG openmls::schedule          > Initializing the key schedule with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ...
 DEBUG openmls::schedule          > Computing EpochSecrets from epoch secret with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::schedule          > Computing confirmation key.
 DEBUG openmls::schedule          > Computing confirmation tag.
 DEBUG msec_relay                 > mls: SimpleMlsAgent { backend: OpenMlsRustCrypto { crypto: RustCrypto { rng: RwLock { data: ChaCha20Rng { rng: BlockRng { core: ChaChaXCore {}, result_len: 64, index: 24 } }, poisoned: false, .. } }, key_store: MemoryKeyStore { values: RwLock { data: {[97, 108, 105, 99, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]: [91, 123, 34, 112, 117, 98, 108, 105, 99, 95, 107, 101, 121, 34, 58, 123, 34, 107, 101, 121, 34, 58, 123, 34, 118, 101, 99, 34, 58, 91, 49, 49, 49, 44, 49, 56, 49, 44, 57, 51, 44, 49, 54, 52, 44, 49, 57, 55, 44, 53, 55, 44, 49, 55, 51, 44, 50, 50, 44, 52, 48, 44, 50, 49, 54, 44, 54, 56, 44, 49, 54, 52, 44, 50, 49, 49, 44, 49, 49, 52, 44, 50, 53, 52, 44, 49, 56, 55, 44, 57, 51, 44, 49, 50, 48, 44, 49, 52, 54, 44, 55, 55, 44, 53, 56, 44, 49, 55, 57, 44, 57, 52, 44, 49, 49, 50, 44, 50, 51, 56, 44, 57, 49, 44, 53, 57, 44, 50, 49, 55, 44, 52, 51, 44, 50, 51, 51, 44, 49, 51, 50, 44, 56, 56, 93, 125, 125, 44, 34, 112, 114, 105, 118, 97, 116, 101, 95, 107, 101, 121, 34, 58, 123, 34, 107, 101, 121, 34, 58, 123, 34, 118, 101, 99, 34, 58, 91, 50, 48, 56, 44, 57, 57, 44, 50, 52, 52, 44, 49, 49, 52, 44, 50, 50, 44, 52, 52, 44, 50, 52, 52, 44, 49, 51, 57, 44, 57, 53, 44, 52, 53, 44, 50, 50, 53, 44, 54, 52, 44, 49, 55, 55, 44, 49, 57, 50, 44, 50, 53, 53, 44, 49, 48, 44, 50, 52, 55, 44, 53, 56, 44, 50, 44, 50, 52, 48, 44, 53, 53, 44, 51, 49, 44, 55, 50, 44, 49, 55, 48, 44, 49, 49, 48, 44, 49, 53, 49, 44, 57, 50, 44, 50, 53, 52, 44, 50, 52, 44, 54, 48, 44, 56, 48, 44, 55, 52, 93, 125, 125, 125, 93], [48, 237, 166, 244, 247, 106, 47, 169, 38, 74, 6, 89, 234, 190, 75, 34, 152, 65, 167, 43, 40, 12, 73, 199, 254, 248, 231, 78, 8, 164, 194, 146, 82, 117, 115, 116, 67, 114, 121, 112, 116, 111, 83, 105, 103, 110, 97, 116, 117, 114, 101, 75, 101, 121, 8, 7]: [123, 34, 112, 114, 105, 118, 97, 116, 101, 34, 58, 91, 51, 48, 44, 49, 48, 55, 44, 50, 51, 48, 44, 49, 55, 53, 44, 50, 53, 50, 44, 49, 49, 54, 44, 49, 57, 57, 44, 49, 50, 50, 44, 49, 51, 44, 49, 53, 50, 44, 51, 56, 44, 49, 50, 57, 44, 54, 53, 44, 50, 51, 50, 44, 49, 51, 56, 44, 50, 48, 50, 44, 50, 48, 53, 44, 49, 51, 49, 44, 49, 51, 53, 44, 50, 44, 57, 52, 44, 49, 52, 55, 44, 49, 53, 54, 44, 52, 53, 44, 55, 51, 44, 49, 48, 48, 44, 49, 49, 55, 44, 49, 52, 51, 44, 52, 53, 44, 49, 51, 50, 44, 49, 51, 55, 44, 55, 54, 93, 44, 34, 112, 117, 98, 108, 105, 99, 34, 58, 91, 52, 56, 44, 50, 51, 55, 44, 49, 54, 54, 44, 50, 52, 52, 44, 50, 52, 55, 44, 49, 48, 54, 44, 52, 55, 44, 49, 54, 57, 44, 51, 56, 44, 55, 52, 44, 54, 44, 56, 57, 44, 50, 51, 52, 44, 49, 57, 48, 44, 55, 53, 44, 51, 52, 44, 49, 53, 50, 44, 54, 53, 44, 49, 54, 55, 44, 52, 51, 44, 52, 48, 44, 49, 50, 44, 55, 51, 44, 49, 57, 57, 44, 50, 53, 52, 44, 50, 52, 56, 44, 50, 51, 49, 44, 55, 56, 44, 56, 44, 49, 54, 52, 44, 49, 57, 52, 44, 49, 52, 54, 93, 44, 34, 115, 105, 103, 110, 97, 116, 117, 114, 101, 95, 115, 99, 104, 101, 109, 101, 34, 58, 34, 69, 68, 50, 53, 53, 49, 57, 34, 125]}, poisoned: false, .. } } }, group_create_config: MlsGroupCreateConfig { capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [ApplicationId, RatchetTree, RequiredCapabilities, ExternalPub, ExternalSenders], proposals: [Add, Update, Remove, PreSharedKey, Reinit, GroupContextExtensions], credentials: [Basic] }, lifetime: Lifetime { not_before: 1708269385, not_after: 1715530585 }, crypto_config: CryptoConfig { ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, version: Mls10 }, join_config: MlsGroupJoinConfig { wire_format_policy: WireFormatPolicy { outgoing: AlwaysCiphertext, incoming: AlwaysCiphertext }, padding_size: 0, max_past_epochs: 0, number_of_resumption_psks: 0, use_ratchet_tree_extension: true, sender_ratchet_configuration: SenderRatchetConfiguration { out_of_order_tolerance: 5, maximum_forward_distance: 1000 } }, group_context_extensions: Extensions { unique: [] }, leaf_node_extensions: Extensions { unique: [] } }, signature_keypair: SignatureKeyPair { private: "***", public: [48, 237, 166, 244, 247, 106, 47, 169, 38, 74, 6, 89, 234, 190, 75, 34, 152, 65, 167, 43, 40, 12, 73, 199, 254, 248, 231, 78, 8, 164, 194, 146], signature_scheme: ED25519 }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x616c696365 } }) }, my_group_id: GroupId { value: VLBytes { 0x616c696365 } }, groups: {GroupId { value: VLBytes { 0x616c696365 } }: MlsGroup { mls_group_config: MlsGroupJoinConfig { wire_format_policy: WireFormatPolicy { outgoing: AlwaysCiphertext, incoming: AlwaysCiphertext }, padding_size: 0, max_past_epochs: 0, number_of_resumption_psks: 0, use_ratchet_tree_extension: true, sender_ratchet_configuration: SenderRatchetConfiguration { out_of_order_tolerance: 5, maximum_forward_distance: 1000 } }, group: CoreGroup { public_group: PublicGroup { treesync: TreeSync { tree: ABinaryTree { leaf_nodes: [TreeSyncLeafNode { node: Some(LeafNode { payload: LeafNodePayload { encryption_key: EncryptionKey { key: VLBytes { 0x6fb55da4c539ad1628d844a4d372febb5d78924d3ab35e70ee5b3bd92be98458 } }, signature_key: SignaturePublicKey { value: VLBytes { 0x30eda6f4f76a2fa9264a0659eabe4b229841a72b280c49c7fef8e74e08a4c292 } }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x616c696365 } }) }, capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [ApplicationId, RatchetTree, RequiredCapabilities, ExternalPub, ExternalSenders], proposals: [Add, Update, Remove, PreSharedKey, Reinit, GroupContextExtensions], credentials: [Basic] }, leaf_node_source: KeyPackage(Lifetime { not_before: 1708269385, not_after: 1715530585 }), extensions: Extensions { unique: [] } }, signature: Signature { value: VLBytes { 0xa94fae8dd8658d771290e0fd148afa2c849d342b98581bb52b2dbb7347bd7ea3e238f073136c34de5491ab3e9ed5ef719b45b253d3042f65056b14dfdec1a60e } } }) }], parent_nodes: [], default_leaf: TreeSyncLeafNode { node: None }, default_parent: TreeSyncParentNode { node: None } }, tree_hash: [57, 249, 169, 136, 144, 167, 14, 235, 78, 192, 83, 106, 184, 72, 124, 247, 190, 157, 151, 87, 205, 228, 112, 210, 120, 166, 14, 19, 108, 33, 199, 220] }, proposal_store: ProposalStore { queued_proposals: [] }, group_context: GroupContext { protocol_version: Mls10, ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, group_id: GroupId { value: VLBytes { 0x616c696365 } }, epoch: GroupEpoch(0), tree_hash: VLBytes { 0x39f9a98890a70eeb4ec0536ab8487cf7be9d9757cde470d278a60e136c21c7dc }, confirmed_transcript_hash: VLBytes { b"" }, extensions: Extensions { unique: [] } }, interim_transcript_hash: [97, 36, 42, 159, 116, 33, 137, 61, 7, 143, 122, 22, 162, 188, 251, 72, 109, 151, 253, 63, 45, 53, 69, 180, 37, 145, 159, 206, 110, 63, 104, 81], confirmation_tag: ConfirmationTag(Mac { mac_value: VLBytes { 0x7ef566b3c21036a131337415ff497646f19662227bd7421b66a0ed76c3d07a92 } }) }, group_epoch_secrets: GroupEpochSecrets { *** }, own_leaf_index: LeafNodeIndex(0), use_ratchet_tree_extension: true, message_secrets_store: MessageSecretsStore { max_epochs: "***", past_epoch_trees: "***", message_secrets: "***" }, resumption_psk_store: ResumptionPskStore { max_number_of_secrets: 32, resumption_psk: [(GroupEpoch(0), ResumptionPskSecret { secret: Secret { ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, value: "***", mls_version: Mls10 } })], cursor: 1 } }, proposal_store: ProposalStore { queued_proposals: [] }, own_leaf_nodes: [], aad: [], group_state: Operational, state_changed: Changed }} }
[...]
 DEBUG msec_relay::transport::group::udpv6                 > via group: 288 bytes from 2001::15
 DEBUG msec_relay::mls                                     > ((( process keypackage from charlie )))
 DEBUG openmls::group::public_group::diff::apply_proposals > Applying proposal
 DEBUG openmls::schedule                                   > Initializing the key schedule with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ...
 DEBUG openmls::schedule                                   > Computing EpochSecrets from epoch secret with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::schedule                                   > Computing confirmation key.
 DEBUG openmls::schedule                                   > Computing confirmation tag.
 DEBUG openmls::framing::private_message                   > PrivateMessage::try_from_authenticated_content
 DEBUG openmls::tree::secret_tree                          > Deriving tree secret for parent node 0 with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::tree::secret_tree                          > Derive tree secret with label "nonce" in generation 0 of length 12
 DEBUG openmls::tree::secret_tree                          > Derive tree secret with label "key" in generation 0 of length 16
 DEBUG openmls::tree::secret_tree                          > Derive tree secret with label "secret" in generation 0 of length 32
 DEBUG openmls::schedule                                   > Getting ciphertext sample of length 32
 DEBUG openmls::schedule                                   > SenderDataSecret::derive_aead_key ciphertext sample: [bf, 6, 67, a2, 15, cd, df, 4e, f3, e, 3c, 46, f7, 7f, ed, 15, ed, c5, 81, 78, b5, 4, 2c, 12, 19, 1d, f5, cc, 62, 76, 8d, f]
 DEBUG openmls::schedule                                   > Getting ciphertext sample of length 32
 DEBUG openmls::schedule                                   > SenderDataSecret::derive_aead_nonce ciphertext sample: [bf, 6, 67, a2, 15, cd, df, 4e, f3, e, 3c, 46, f7, 7f, ed, 15, ed, c5, 81, 78, b5, 4, 2c, 12, 19, 1d, f5, cc, 62, 76, 8d, f]
 DEBUG msec_relay::mls                                     > MlsMessageOut { version: Mls10, body: PrivateMessage(PrivateMessage { group_id: GroupId { value: VLBytes { 0x616c696365 } }, epoch: GroupEpoch(1), content_type: Commit, authenticated_data: VLBytes { b"" }, encrypted_sender_data: VLBytes { 0x383e45523a1b219e3647c9560880f6e6c3bcce19879b5bcc95c60d79 }, ciphertext: VLBytes { 0xbf0667a215cddf4ef30e3c46f77fed15edc58178b5042c12191df5cc62768d0f90dd8f714834c2258dcf742468597befffe22a40152eb018d1a148f887e09d1db70a402937bbaca969170a1c6bc4eaac858264234f97415fa7d1782a90ff79105eeffe1a487658726783a0ebf0d2dc1451e36c6b932059daa331215bfca4e9f8fe2ca8e9acb48df56eacb666c095b5387415705dc2dc6acea58e42fc37be3bba582a65d363174fb19c2fbe3275823d12b6ec9edc1414314e532cfa8bdcbbca1595354ee4d04720a67832f2905d3237ff6d7a8baf6df17df7fcfcbcf330e5664accb02b37709d955bb5ac3dfaf4bebfb0b1342e748e99f967db1a18d9a16fd224e3a253e45b87ee8910b958c042de02ce861d2ad8d69731dee0bb16a19556612398fe6fcac0b3ce5db128a5d7989f114ab80e97fa3bd20a6658f9e051e6653ec7453a3e5e53799784d1c8303268941883d0c9113b38662ca8ddcc995e330cf0f1cba7eb0879bcbe0df2f3c62c052ffee0c016e581331a97fa2c0859aea4ed0c4ceecfee5f969cf7fad2651c984406e1a0d5bec753ab5530739e12aed5edef392587c0318437f3b9842524fcc062dbb04842262111dabb7ca2845c42d7690df32084ee92c07c48991248582601fd4aa39acc4951fd25b73fdd1f608eb260757869a9e19d98d4476bd6ceef2bce962ee8e35f7d3a8ba532c95906f77955d762979fbea70445ebe286b80da9690f3bd21163519cee2c24ef86b79f4e1bc7f378c1a941a5b6705e9ff693a25af16bda80a1edfaa28288a9d69348e9e1b33dae666eb5fc97298c0fcbee9332b429be784fded91e35dba1eafd5cf056ab7f66cf5eeecc11c52034039565859e9ba42101b96f192958e4dad76088159ea7c88a130287222adc516d993fb43dcfe7e99b0f0c367172d31404d02e27144155def57bc643b2a4a064e985a4dd2ac0e8350b20915dfed0eda2daf84822fdb8d79b1aec7f77cf38d4b40faeabdfada0874022bc20bab4fcae25ec2d8a730f67fcfca38a8fcc628db4b33fb5690df055f9f9fbb347d55e933e162a46822aefb32649a7ce7d83528928 } }) }
 DEBUG msec_relay::mls                                     > MlsMessageOut { version: Mls10, body: Welcome(Welcome { cipher_suite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, secrets: [EncryptedGroupSecrets { new_member: HashReference: 2937ED396C7EE267C35F4F74D9CD1A79CA4783CAAD1D69FC11CD2B5255353296, encrypted_group_secrets: HpkeCiphertext { kem_output: VLBytes { 0x798fa9f1a142d23485078127910173c77388419d9a7fe86c263b1f904a40946b }, ciphertext: VLBytes { 0xfc9147b8c3b6ee47d874603f543ae13b4b0e8d5a8cb913a6b2bd5978827b00e741551ade72f78a5e5f665b9239e4fdc102b5a2dba79250158fb077243088f25a5c3df1ed84cf6abd3346f4ea41de93d944695fa7 } } }], encrypted_group_info: VLBytes { 0xdeb4b2c9d547fea09a95711f3861ed6ae12db2c5e29f0bddcae8380c20db588d2beaba183bb9f60d56cf585562e57e6423e67fb4c7032b4899ae59121ad10c05794f10edd72bc62c8ba6502bac45b11b2494305e697b28c3b01e2c0f86356325122a5298f2f453100f60e421142e428b8d1bd58b51dc9efabd704e881b2d4e473f5d176437af1ec2cb28e88dd8e80fe55f2f2c1a81ba4168faa8ca0a1f9f5145fe3a9c1f12657ff3989e718be592029d08511e8b8ca291eb91b8b14dd36cc0efc239da33b9746c6123f5c8773a6767cb4459b1c081df9e87955b024777225f04ea9710e37e0051cd29943e0a2b80387d111a7ed409b87c64eb10607a51a375a9e8e2bb5c6ebe262b5c159ef2ad46e204d8715050964bbca2510c5a00b68903566564fca0302ef013af1072b7486873c23964190ec7c7086e49d14cc7a9e029de2f39d89e28d03840efea528bdc8688c8e6ca33cabc9a794289bd40119fbfd34d9256e9b595397a182316462422a64edbcc9b6c12cdb932ee72e9063555bd2a77fd7c6de79c20ca958a72b5947643cbf6396f6298fec3b40633483cbc4d1808a1299ce18d99a31d4156aaf3ddcc87d23734cb90f3045937e2607e0e74dfb1a47aabf5d1f4fcc74f61395ab1b9317ce2be4c79894cd86c0eac96b6f4bb4f5d43953231eb69fcdb01d7b5c8c2ef9f2051db7177e8d0d46b46e4134ae754aea7c2f818adebf7daeee6cd8bdb77d72f2501a590c25e497c6965eaa121669925b071c67080f9b7b351aa51d4441842cffede58d80690421dbdfa0549c3e62d25e6b2f8891e98334bc937db39349003da15e7532a25b16a488219a527c20f9a7f560a77267d758140f80c03c1f93af6c8059d636a789b10f38338677c64fb2350d605cc35c531de4c178c1f378cdbf6550a1e6912d569b00b4f13ceea82c8baaf9257915f67e14a8620412a7d97ecbeacb6b138a2cb010575363067534d39bf5bfeec515f8bcebe5b88ec2112ff1ec93fe134c3adf5f03ae5c54ab3f03086ed5b641d8207b5a2466103f50dbb5ccf697c7270f1bcb44dd94dc0d41a0a3154ec01489ff88d4bf8f5bc681c2da31a5eb4e9f1aafa8e050b3fe79723fae28f060a939e822f2de4a1ffd54c7e2b15a475863fdcbfd07e56c07c04d8e30479d7a2a54cc7bd76e851311cb8971357b71c40d33a18c287e480824fcbeec8eacdfe210ac5003d833f84722e8096285fa35cf755622ac66be96d28c33539983482df4954cdfbdcb8651d92c4a85879d174495327386e2c9af0160e41a32022b8a4ee } }) }
 DEBUG msec_relay::transport::group::udpv6                 > to group: 821 bytes
 DEBUG msec_relay::transport::p2p::tcpv6                   > via p2p: 1084 bytes to [2001::15]:18001
```
On bob:
```bash
 DEBUG openmls::group::core_group > Created group GroupId { value: VLBytes { 0x626f62 } }
 DEBUG openmls::schedule          > Initializing the key schedule with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ...
 DEBUG openmls::schedule          > Computing EpochSecrets from epoch secret with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::schedule          > Computing confirmation key.
 DEBUG openmls::schedule          > Computing confirmation tag.
 DEBUG msec_relay                 > mls: SimpleMlsAgent { backend: OpenMlsRustCrypto { crypto: RustCrypto { rng: RwLock { data: ChaCha20Rng { rng: BlockRng { core: ChaChaXCore {}, result_len: 64, index: 24 } }, poisoned: false, .. } }, key_store: MemoryKeyStore { values: RwLock { data: {[98, 111, 98, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]: [91, 123, 34, 112, 117, 98, 108, 105, 99, 95, 107, 101, 121, 34, 58, 123, 34, 107, 101, 121, 34, 58, 123, 34, 118, 101, 99, 34, 58, 91, 49, 54, 44, 52, 52, 44, 50, 49, 51, 44, 53, 48, 44, 53, 48, 44, 49, 54, 53, 44, 50, 48, 57, 44, 56, 55, 44, 50, 50, 56, 44, 51, 56, 44, 49, 50, 54, 44, 49, 49, 52, 44, 54, 52, 44, 49, 57, 49, 44, 49, 52, 51, 44, 49, 49, 54, 44, 49, 49, 51, 44, 54, 52, 44, 49, 55, 54, 44, 49, 53, 49, 44, 50, 50, 50, 44, 53, 55, 44, 50, 51, 53, 44, 49, 51, 51, 44, 49, 52, 44, 49, 53, 55, 44, 52, 51, 44, 49, 53, 57, 44, 49, 48, 49, 44, 57, 51, 44, 49, 55, 57, 44, 49, 48, 56, 93, 125, 125, 44, 34, 112, 114, 105, 118, 97, 116, 101, 95, 107, 101, 121, 34, 58, 123, 34, 107, 101, 121, 34, 58, 123, 34, 118, 101, 99, 34, 58, 91, 50, 51, 56, 44, 49, 56, 54, 44, 50, 48, 49, 44, 49, 49, 48, 44, 56, 51, 44, 49, 55, 56, 44, 51, 55, 44, 54, 48, 44, 49, 56, 57, 44, 53, 53, 44, 53, 54, 44, 50, 51, 55, 44, 52, 55, 44, 54, 55, 44, 49, 54, 50, 44, 49, 48, 53, 44, 50, 52, 50, 44, 53, 55, 44, 49, 54, 52, 44, 49, 57, 44, 49, 53, 44, 49, 54, 56, 44, 49, 57, 55, 44, 49, 51, 56, 44, 49, 56, 44, 50, 49, 57, 44, 50, 50, 50, 44, 49, 54, 48, 44, 49, 53, 48, 44, 49, 51, 49, 44, 49, 54, 49, 44, 57, 48, 93, 125, 125, 125, 93], [168, 42, 211, 52, 147, 235, 79, 65, 134, 121, 131, 139, 33, 90, 192, 172, 56, 247, 177, 192, 31, 163, 47, 210, 121, 23, 100, 227, 171, 43, 69, 171, 82, 117, 115, 116, 67, 114, 121, 112, 116, 111, 83, 105, 103, 110, 97, 116, 117, 114, 101, 75, 101, 121, 8, 7]: [123, 34, 112, 114, 105, 118, 97, 116, 101, 34, 58, 91, 52, 56, 44, 49, 57, 50, 44, 50, 49, 49, 44, 49, 51, 44, 56, 50, 44, 49, 53, 57, 44, 52, 56, 44, 49, 56, 51, 44, 51, 49, 44, 52, 57, 44, 52, 51, 44, 49, 57, 44, 50, 50, 48, 44, 50, 51, 55, 44, 50, 50, 49, 44, 49, 52, 52, 44, 50, 53, 52, 44, 49, 54, 54, 44, 49, 52, 53, 44, 50, 48, 48, 44, 49, 57, 51, 44, 57, 56, 44, 50, 49, 57, 44, 57, 52, 44, 49, 52, 48, 44, 55, 49, 44, 50, 52, 53, 44, 55, 51, 44, 49, 50, 44, 54, 50, 44, 49, 48, 53, 44, 48, 93, 44, 34, 112, 117, 98, 108, 105, 99, 34, 58, 91, 49, 54, 56, 44, 52, 50, 44, 50, 49, 49, 44, 53, 50, 44, 49, 52, 55, 44, 50, 51, 53, 44, 55, 57, 44, 54, 53, 44, 49, 51, 52, 44, 49, 50, 49, 44, 49, 51, 49, 44, 49, 51, 57, 44, 51, 51, 44, 57, 48, 44, 49, 57, 50, 44, 49, 55, 50, 44, 53, 54, 44, 50, 52, 55, 44, 49, 55, 55, 44, 49, 57, 50, 44, 51, 49, 44, 49, 54, 51, 44, 52, 55, 44, 50, 49, 48, 44, 49, 50, 49, 44, 50, 51, 44, 49, 48, 48, 44, 50, 50, 55, 44, 49, 55, 49, 44, 52, 51, 44, 54, 57, 44, 49, 55, 49, 93, 44, 34, 115, 105, 103, 110, 97, 116, 117, 114, 101, 95, 115, 99, 104, 101, 109, 101, 34, 58, 34, 69, 68, 50, 53, 53, 49, 57, 34, 125]}, poisoned: false, .. } } }, group_create_config: MlsGroupCreateConfig { capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [ApplicationId, RatchetTree, RequiredCapabilities, ExternalPub, ExternalSenders], proposals: [Add, Update, Remove, PreSharedKey, Reinit, GroupContextExtensions], credentials: [Basic] }, lifetime: Lifetime { not_before: 1708269391, not_after: 1715530591 }, crypto_config: CryptoConfig { ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, version: Mls10 }, join_config: MlsGroupJoinConfig { wire_format_policy: WireFormatPolicy { outgoing: AlwaysCiphertext, incoming: AlwaysCiphertext }, padding_size: 0, max_past_epochs: 0, number_of_resumption_psks: 0, use_ratchet_tree_extension: true, sender_ratchet_configuration: SenderRatchetConfiguration { out_of_order_tolerance: 5, maximum_forward_distance: 1000 } }, group_context_extensions: Extensions { unique: [] }, leaf_node_extensions: Extensions { unique: [] } }, signature_keypair: SignatureKeyPair { private: "***", public: [168, 42, 211, 52, 147, 235, 79, 65, 134, 121, 131, 139, 33, 90, 192, 172, 56, 247, 177, 192, 31, 163, 47, 210, 121, 23, 100, 227, 171, 43, 69, 171], signature_scheme: ED25519 }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x626f62 } }) }, my_group_id: GroupId { value: VLBytes { 0x626f62 } }, groups: {GroupId { value: VLBytes { 0x626f62 } }: MlsGroup { mls_group_config: MlsGroupJoinConfig { wire_format_policy: WireFormatPolicy { outgoing: AlwaysCiphertext, incoming: AlwaysCiphertext }, padding_size: 0, max_past_epochs: 0, number_of_resumption_psks: 0, use_ratchet_tree_extension: true, sender_ratchet_configuration: SenderRatchetConfiguration { out_of_order_tolerance: 5, maximum_forward_distance: 1000 } }, group: CoreGroup { public_group: PublicGroup { treesync: TreeSync { tree: ABinaryTree { leaf_nodes: [TreeSyncLeafNode { node: Some(LeafNode { payload: LeafNodePayload { encryption_key: EncryptionKey { key: VLBytes { 0x102cd53232a5d157e4267e7240bf8f747140b097de39eb850e9d2b9f655db36c } }, signature_key: SignaturePublicKey { value: VLBytes { 0xa82ad33493eb4f418679838b215ac0ac38f7b1c01fa32fd2791764e3ab2b45ab } }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x626f62 } }) }, capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [ApplicationId, RatchetTree, RequiredCapabilities, ExternalPub, ExternalSenders], proposals: [Add, Update, Remove, PreSharedKey, Reinit, GroupContextExtensions], credentials: [Basic] }, leaf_node_source: KeyPackage(Lifetime { not_before: 1708269391, not_after: 1715530591 }), extensions: Extensions { unique: [] } }, signature: Signature { value: VLBytes { 0x9d98923243c5a18f72f62f8d03bf3188e2f8da95c580c8307716566579deb018f927b70b278825ba12668098ff368019a4f423d88d06098feef0f0e5c71fb400 } } }) }], parent_nodes: [], default_leaf: TreeSyncLeafNode { node: None }, default_parent: TreeSyncParentNode { node: None } }, tree_hash: [83, 100, 159, 217, 234, 206, 101, 216, 219, 131, 97, 128, 193, 14, 211, 157, 56, 2, 154, 28, 241, 137, 221, 217, 1, 188, 2, 141, 172, 53, 52, 156] }, proposal_store: ProposalStore { queued_proposals: [] }, group_context: GroupContext { protocol_version: Mls10, ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, group_id: GroupId { value: VLBytes { 0x626f62 } }, epoch: GroupEpoch(0), tree_hash: VLBytes { 0x53649fd9eace65d8db836180c10ed39d38029a1cf189ddd901bc028dac35349c }, confirmed_transcript_hash: VLBytes { b"" }, extensions: Extensions { unique: [] } }, interim_transcript_hash: [199, 242, 111, 238, 250, 199, 184, 43, 228, 76, 110, 253, 216, 236, 29, 195, 53, 197, 229, 112, 100, 11, 83, 42, 191, 27, 79, 141, 130, 164, 32, 53], confirmation_tag: ConfirmationTag(Mac { mac_value: VLBytes { 0xe3334873c2385596ff62744c759782f6863de08e2caac8275ceb9f7448df60cc } }) }, group_epoch_secrets: GroupEpochSecrets { *** }, own_leaf_index: LeafNodeIndex(0), use_ratchet_tree_extension: true, message_secrets_store: MessageSecretsStore { max_epochs: "***", past_epoch_trees: "***", message_secrets: "***" }, resumption_psk_store: ResumptionPskStore { max_number_of_secrets: 32, resumption_psk: [(GroupEpoch(0), ResumptionPskSecret { secret: Secret { ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, value: "***", mls_version: Mls10 } })], cursor: 1 } }, proposal_store: ProposalStore { queued_proposals: [] }, own_leaf_nodes: [], aad: [], group_state: Operational, state_changed: Changed }} }
[...]
 DEBUG msec_relay::transport::group::udpv6                 > via group: 288 bytes from 2001::15
 DEBUG msec_relay::mls                                     > ((( process keypackage from charlie )))
 DEBUG openmls::group::public_group::diff::apply_proposals > Applying proposal
 DEBUG openmls::schedule                                   > Initializing the key schedule with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ...
 DEBUG openmls::schedule                                   > Computing EpochSecrets from epoch secret with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::schedule                                   > Computing confirmation key.
 DEBUG openmls::schedule                                   > Computing confirmation tag.
 DEBUG openmls::framing::private_message                   > PrivateMessage::try_from_authenticated_content
 DEBUG openmls::tree::secret_tree                          > Deriving tree secret for parent node 0 with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::tree::secret_tree                          > Derive tree secret with label "nonce" in generation 0 of length 12
 DEBUG openmls::tree::secret_tree                          > Derive tree secret with label "key" in generation 0 of length 16
 DEBUG openmls::tree::secret_tree                          > Derive tree secret with label "secret" in generation 0 of length 32
 DEBUG openmls::schedule                                   > Getting ciphertext sample of length 32
 DEBUG openmls::schedule                                   > SenderDataSecret::derive_aead_key ciphertext sample: [b7, 65, 49, 5f, 67, 4e, 5d, a4, fd, d3, 99, 8b, 35, c6, dd, 22, 7f, 47, 43, 6e, 88, 4b, 95, 0, eb, 94, 7f, ee, fb, 3a, e6, 1b]
 DEBUG openmls::schedule                                   > Getting ciphertext sample of length 32
 DEBUG openmls::schedule                                   > SenderDataSecret::derive_aead_nonce ciphertext sample: [b7, 65, 49, 5f, 67, 4e, 5d, a4, fd, d3, 99, 8b, 35, c6, dd, 22, 7f, 47, 43, 6e, 88, 4b, 95, 0, eb, 94, 7f, ee, fb, 3a, e6, 1b]
 DEBUG msec_relay::mls                                     > MlsMessageOut { version: Mls10, body: PrivateMessage(PrivateMessage { group_id: GroupId { value: VLBytes { 0x626f62 } }, epoch: GroupEpoch(1), content_type: Commit, authenticated_data: VLBytes { b"" }, encrypted_sender_data: VLBytes { 0x7ec22a0a2e9ce559fcac231d080e63a82f32e1eb59462b5848bc884f }, ciphertext: VLBytes { 0xb765495f674e5da4fdd3998b35c6dd227f47436e884b9500eb947feefb3ae61bd1ba08efbb50b3816d0d3495c4713f9139ee3394793af3fb84df06b52c89893d4a3b881551bb97c83b6957a9d37a3cde0f23745e0aa7ae93e4f9bd18bf38b0590b1238314773f0ad06f4a77f3e807ac811d01b71297592a9b3f6d6545a054bce9f2fdf5b25785445c1a52fc1f4c5128ff62cc5fbc923985eada0dbcbe839c555b9e9b7611fa9ecab4e6bd1f81dbcd15961b40788f477437db57d8688c14d5ef5e21e13cb688f687bf71bfb2b97674c93367d17669080ad292c48f5b0be08c2f63a11a1b90e5cb43a93a918d1ddd6c445dea68b670d407c4efe5ff6a0501b4b7d67264769239345c3efa76732887c2f0bd678281ff14c01a02703fa46579733105f7f05dcde79c2314e48b128e292cf75fae6a17d0583f88d9bbfa1248cd728b751664ac242e66ca9f374eccaa8a6fa73c7f29a3ff44d407793c12d9485f8d47cea71c3bba863de65170bab91c1baedf9b5eeca5e617b4f216effc970c017d3e95186376231afd4fa2f8d0206fea3d93fbc9329139377b332e399b43e0778b209d975e52baf0276f02f134b9f5c708b2025e462b2e2ac39c1c0d50b9ffc08202db65dfc5f7e239c2a6d5a2ff313e5fe61522babad06dbd26f5645af22ed028e768a20b5cd7518e4ebf2171e36684e375396e19d4dde1bd8b3eb68cff2ea29f9336d94183bac3f2d397272448072bedfd6a18f1fe5774ae4fdd76efcf5eab95ac3d7cbc4a10935a232f7f0b70fd46d108876bee18fc52b18f270ac640ac96042176367eae48aa41c049a78236905c15020fc9025911e1575229ed0c7e3e046246ff2917084d2680ea2bbb0a0272e9afcf83c8363ebf0a939d3e0279712b29ea48f907256fbfe6d894850bfc8a0ba9e591fdbc8766c91ae09a36d541e341b558a02174947c405e70f8bf23c0afb63aced7f235fda65fc0caacaf23d31dbf56fafa7bb3f8df6475399dc24f8c62688883c09d82637212fb676bed920aa25284bef066cd8ab223c63042ac412a20701ffe0bc521b4948f7d64d13592f3d93b31e305b } }) }
 DEBUG msec_relay::mls                                     > MlsMessageOut { version: Mls10, body: Welcome(Welcome { cipher_suite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, secrets: [EncryptedGroupSecrets { new_member: HashReference: 2937ED396C7EE267C35F4F74D9CD1A79CA4783CAAD1D69FC11CD2B5255353296, encrypted_group_secrets: HpkeCiphertext { kem_output: VLBytes { 0x9a6891ced7b8217f24432c415fa3fb98796926d7dc31eef9241f879f62152a3e }, ciphertext: VLBytes { 0x02054908942e1416cbfbaf8156fc3c19a10640fb22a5eeb4adc6fa17683d937c919d92b1e8433cff5b7f8c086ffe15e86b8d7ffa396e4a92c9c8e29c1ddf62dd0ae7802b7210afb5dcf2d6716287f5c01318fcd5 } } }], encrypted_group_info: VLBytes { 0xc36678d09aa9541d4100bbf346a96bd5c1aa2a862472dffe103da53772e527d81ca834a7c417030f752a250ddde368f292ec952d2b0910d8cdef7e921a9d70875e239f05088aeeb6759646899384b9b2651fe646d4c6b89788ba31988a8f605e8c875939f3b34b1d6f068e549a40707e7503991a1384efb58c82fc7ae4fd46930ad1671efab05549cdafc18b04cff1b16540b913a2e477729731cad7ba50c7dd49cfb759f5a99895ff03c350f9e05c2b9e403436c25d5295d09dd7c69c120041515b52cb7e3980aeb636fd75228e8810d3cb6a6906f7b9ef6ec3997e004e3c93d34f3f97b0138961b7c4ce07db5b368c4fda3dfedf5c3f76f5c4317246f3cbbe215225814e105190dce58400abc1fe7401b3c611511d31d03a58b43dd4a354fdd9ddfe793bbd34e9a00ba45b7e04212cd15645426a8852cd5f37a19420aa43d23bc60c16fa2763ce222a1d38ae6464c0ef345385f3001df6691c0ef750e7390b6b7fd00bf7a7502817064719af877e8bc7b8ae8e63b42ef60a7a77c8c8d6a60237adb59749afff215ce36edc8560caa31f3bb168dae5575fefc75341c15845a9cc23396556d81fdcc02a74a5b47317fe978eb4fadf98f004bc201f50db1747ba35ac4298d0d130d13598d3724809ec6ca7cea0d6401581005de22e6acd3bea41cddb5bb15b7584c98361015cfdeab8aa46c00f2be30f37d7242828fb05bf7bef1d06483c3ed846401e1812fa5cef784f522063336e9d3bc9e4884717a07b824c3a437d12d52d805de0bce683388a4cee4664da1997ba38dadccc655058daa7e9f03c9d7846ce7936e86977ae6e087f41b5fcf5d26d7f772818ec8c22adfbe86a2c669d02d8335af09357879f11db4374ef97077a0ca5fd40885f67198becec43c95ebec76f6e6cd7546efa8c33420b9a56edaaf526a0b172b6afd8706cc0cec9acef5b7c9ac321c198f5b8273af8fcfe2bf691bdb6c424ba74f2b4f935a28d7d1d258b5068d24e30e78169c0bf9a5f8a24a9c78430450fdf6f780559d743a6f31ed51f6a48f1d024fec455907332a967ff851df4d0f9aff099c7de0ec6fe95d2c044f4b346a87cfe58af40272afd5c4abd960191e743e3293fdb97cafea54f6920055b8517091bdf89137befed5da70bc7034ff454ab139fa51026a27406697f74f0b0a984557bc2709442d9b41f9159fa389bb40120db312cac312fd06f123bb4e9150b848f63531a4b4900d416e9dbf51bd3a87d4e26445e81a6cde231db5a87f68b4eaed64782782f2172a6e450d0d5ce57461a2428f0 } }) }
 DEBUG msec_relay::transport::group::udpv6                 > to group: 817 bytes
 DEBUG msec_relay::transport::p2p::tcpv6                   > via p2p: 1082 bytes to [2001::15]:18001
```
On charlie:
```bash
 DEBUG msec_relay::mls            > KeyPackage { payload: KeyPackageTbs { protocol_version: Mls10, ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, init_key: VLBytes { 0xf8b9fc0516e45ff7f645575944ecf8554f86271885bb1c91c492ae1f1de8d50d }, leaf_node: LeafNode { payload: LeafNodePayload { encryption_key: EncryptionKey { key: VLBytes { 0x76da234217196720c69f0b3bd6d3937c41362600a8226d7a3548f2d4e7ab190f } }, signature_key: SignaturePublicKey { value: VLBytes { 0xf1cf4f7c2ece084cdfeb45c8f49e8b3336c78b910eb130c2ecd23c133fe6947e } }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x636861726c6965 } }) }, capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [LastResort], proposals: [], credentials: [Basic] }, leaf_node_source: KeyPackage(Lifetime { not_before: 1708269396, not_after: 1715530596 }), extensions: Extensions { unique: [] } }, signature: Signature { value: VLBytes { 0x70d3aa4dcdf4ff97e2c8c26c4df43129db27c1fcd56b3c8e67183c40f7abcc45dc4efba53a54d23860e7c5c6b7c8a11514e802fbee547a8392a4518f6c06c704 } } }, extensions: Extensions { unique: [LastResort(LastResortExtension)] } }, signature: Signature { value: VLBytes { 0x6956fa045f5787c5184c4a1bda606b3dac21149ece7db60a4e2e8da796aa84c0e375131024e5136610726e27358344e8871f2d3b50fe07ee646c95cfa2a57e00 } } }
 DEBUG msec_relay::transport::group::udpv6 > to group: 288 bytes
 DEBUG msec_relay::transport::group::udpv6 > via group: 817 bytes from 2001::16
 DEBUG msec_relay::transport::group::udpv6 > via group: 821 bytes from 2001::14
 DEBUG msec_relay::transport::p2p::tcpv6   > via p2p: 1082 bytes from 2001::16
 DEBUG msec_relay::mls                     > ((( process protomsg in group GroupId { value: VLBytes { 0x626f62 } }... )))
 DEBUG msec_relay::mls                     > ((( group is UNKNOWN to me )))
 DEBUG msec_relay::mls                     > ((( process protomsg in group GroupId { value: VLBytes { 0x616c696365 } }... )))
 DEBUG msec_relay::mls                     > ((( group is UNKNOWN to me )))
 DEBUG msec_relay::transport::p2p::tcpv6   > via p2p: 1084 bytes from 2001::14
 DEBUG msec_relay::mls                     > ((( process welcome )))
 DEBUG openmls::group::mls_group::creation > Key package has last resort extension, not deleting
 DEBUG openmls::group::core_group::new_from_welcome > CoreGroup::new_from_welcome_internal
 DEBUG openmls::schedule                            > Initializing the key schedule with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ...
 DEBUG openmls::schedule                            > Computing EpochSecrets from epoch secret with MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
 DEBUG openmls::schedule                            > Computing confirmation key.
 DEBUG openmls::schedule                            > Computing confirmation tag.
 DEBUG msec_relay::mls                              > MlsGroup { mls_group_config: MlsGroupJoinConfig { wire_format_policy: WireFormatPolicy { outgoing: AlwaysCiphertext, incoming: AlwaysCiphertext }, padding_size: 0, max_past_epochs: 0, number_of_resumption_psks: 0, use_ratchet_tree_extension: true, sender_ratchet_configuration: SenderRatchetConfiguration { out_of_order_tolerance: 5, maximum_forward_distance: 1000 } }, group: CoreGroup { public_group: PublicGroup { treesync: TreeSync { tree: ABinaryTree { leaf_nodes: [TreeSyncLeafNode { node: Some(LeafNode { payload: LeafNodePayload { encryption_key: EncryptionKey { key: VLBytes { 0x692bc4db604dd6fedbebd6bac4333365ba448f379427352d16c1b9fd89128841 } }, signature_key: SignaturePublicKey { value: VLBytes { 0xa82ad33493eb4f418679838b215ac0ac38f7b1c01fa32fd2791764e3ab2b45ab } }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x626f62 } }) }, capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [ApplicationId, RatchetTree, RequiredCapabilities, ExternalPub, ExternalSenders], proposals: [Add, Update, Remove, PreSharedKey, Reinit, GroupContextExtensions], credentials: [Basic] }, leaf_node_source: Commit(VLBytes { 0x592ec031107b6f0ff01aa2410a65a46c939afc7f5b29feb1cfe884eee98fb64b }), extensions: Extensions { unique: [] } }, signature: Signature { value: VLBytes { 0x76630f303a7fbb18a13eb07c0994b5fde09ed10e245f2676488277cde55397e5a10ace82f3dc5ef933f3c6086e4093d9d5a143128d96643c366dfbf7549c0d07 } } }) }, TreeSyncLeafNode { node: Some(LeafNode { payload: LeafNodePayload { encryption_key: EncryptionKey { key: VLBytes { 0x96b23431c80ce810c0420c29e6230b915c14bbdfc56af191883f84b113baba2b } }, signature_key: SignaturePublicKey { value: VLBytes { 0x30eda6f4f76a2fa9264a0659eabe4b229841a72b280c49c7fef8e74e08a4c292 } }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x616c696365 } }) }, capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [LastResort], proposals: [], credentials: [Basic] }, leaf_node_source: KeyPackage(Lifetime { not_before: 1708269395, not_after: 1715530595 }), extensions: Extensions { unique: [] } }, signature: Signature { value: VLBytes { 0x850a66335365042546b7cd7a355559d3b13bd3618f20154fd1a143f949495813732094dc812aad95f415f1f00ee75c2a934ec0129b161dbdb4447ebe514d3f07 } } }) }, TreeSyncLeafNode { node: Some(LeafNode { payload: LeafNodePayload { encryption_key: EncryptionKey { key: VLBytes { 0x76da234217196720c69f0b3bd6d3937c41362600a8226d7a3548f2d4e7ab190f } }, signature_key: SignaturePublicKey { value: VLBytes { 0xf1cf4f7c2ece084cdfeb45c8f49e8b3336c78b910eb130c2ecd23c133fe6947e } }, credential: Credential { credential_type: Basic, credential: Basic(BasicCredential { identity: VLBytes { 0x636861726c6965 } }) }, capabilities: Capabilities { versions: [Mls10], ciphersuites: [VerifiableCiphersuite(1), VerifiableCiphersuite(2), VerifiableCiphersuite(3)], extensions: [LastResort], proposals: [], credentials: [Basic] }, leaf_node_source: KeyPackage(Lifetime { not_before: 1708269396, not_after: 1715530596 }), extensions: Extensions { unique: [] } }, signature: Signature { value: VLBytes { 0x70d3aa4dcdf4ff97e2c8c26c4df43129db27c1fcd56b3c8e67183c40f7abcc45dc4efba53a54d23860e7c5c6b7c8a11514e802fbee547a8392a4518f6c06c704 } } }) }, TreeSyncLeafNode { node: None }], parent_nodes: [TreeSyncParentNode { node: Some(ParentNode { encryption_key: EncryptionKey { key: VLBytes { 0x5ee763b546036b7cca25da35549dda7c1190f1f9886b3c0c388cee50ce42af16 } }, parent_hash: VLBytes { 0xa0836e14aa5aad130d24dfb0a47c566417862a58b564c151b46d46ea38062a7c }, unmerged_leaves: UnmergedLeaves { list: [] } }) }, TreeSyncParentNode { node: Some(ParentNode { encryption_key: EncryptionKey { key: VLBytes { 0x974675eac3ce2ebd898b77bcae2e318d437d141e80b140a72a0405c4f5140e18 } }, parent_hash: VLBytes { b"" }, unmerged_leaves: UnmergedLeaves { list: [] } }) }, TreeSyncParentNode { node: None }], default_leaf: TreeSyncLeafNode { node: None }, default_parent: TreeSyncParentNode { node: None } }, tree_hash: [4, 213, 194, 88, 24, 133, 153, 199, 6, 151, 10, 42, 203, 66, 20, 216, 231, 96, 176, 53, 110, 134, 165, 183, 101, 173, 122, 70, 40, 228, 97, 73] }, proposal_store: ProposalStore { queued_proposals: [] }, group_context: GroupContext { protocol_version: Mls10, ciphersuite: MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519, group_id: GroupId { value: VLBytes { 0x626f62 } }, epoch: GroupEpoch(2), tree_hash: VLBytes { 0x04d5c258188599c706970a2acb4214d8e760b0356e86a5b765ad7a4628e46149 }, confirmed_transcript_hash: VLBytes { 0x412c5796fe0b7ceac02b83ad174836727e42d57e71196510441b8744465680df }, extensions: Extensions { unique: [] } }, interim_transcript_hash: [222, 181, 31, 171, 112, 195, 252, 195, 150, 63, 114, 204, 240, 109, 159, 15, 207, 25, 99, 173, 39, 126, 40, 144, 211, 54, 45, 215, 151, 120, 61, 58], confirmation_tag: ConfirmationTag(Mac { mac_value: VLBytes { 0xf38005f8c103555aebe7094eac6a0d05cf3b5d948d9b903aa006b6498786a630 } }) }, group_epoch_secrets: GroupEpochSecrets { *** }, own_leaf_index: LeafNodeIndex(2), use_ratchet_tree_extension: true, message_secrets_store: MessageSecretsStore { max_epochs: "***", past_epoch_trees: "***", message_secrets: "***" }, resumption_psk_store: ResumptionPskStore { max_number_of_secrets: 0, resumption_psk: [], cursor: 0 } }, proposal_store: ProposalStore { queued_proposals: [] }, own_leaf_nodes: [], aad: [], group_state: Operational, state_changed: Changed }
 DEBUG msec_relay::mls                              > ((( process welcome )))
 DEBUG openmls::group::mls_group::creation          > Key package has last resort extension, not deleting
 DEBUG openmls::group::core_group::new_from_welcome > CoreGroup::new_from_welcome_internal
 ERROR msec_relay                                   > in group processing thread: No matching encryption key was found in the key store.
```

**Platform (please complete the following information):**
 - OS & OS version: Ubuntu 22.04
 - Architecture: x86_64
 - Version: openmls commit e7578f46

**Additional context**
Definitely not an OpenMLS expert, so let me know else would be required to adjudicate this issue.  My application (`msec_relay`) is currently private but happy to provide additional info on request.

Thanks again!

### PR DESCRIPTION
**Pull request by josephlukefahr**
Closes #1502 

This PR just copies the logic in group::MlsGroup::new_from_welcome(...), which checks for last resort extension in keypackage, to group::CoreGroup::new_from_welcome(...).

### CODE REVIEW

**Comment by kkohbrok** [comment]
Thanks for the PR! It looks like it solves the issue. To confirm that it does and to ensure we don't run into this sort of thing in the future, would you be so kind as to add a simple test? You can add the test to `mls_group/test_mls_group.rs`, where you can find inspiration on how to set up the test as well. I think it's better to have the test at the `MlsGroup` (rather than the `CoreGroup`) level, since we're likely to move all provider access to `MlsGroup` level eventually anyway (see #1207).

**Review by kkohbrok — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks like it solves the issue. To confirm that it does and to ensure we don't run into this sort of thing in the future, would you be so kind as to add a simple test? You can add the test to `mls_group/test_mls_group.rs`, where you can find inspiration on how to set up the test as well. I think it's better to have the test at the `MlsGroup` (rather than the `CoreGroup`) level, since we're likely to move all provider access to `MlsGroup` level eventually anyway (see #1207).

(Also you'll have to run `cargo fmt` on the code before we can merge.)

File: openmls/src/group/core_group/new_from_welcome.rs [hunk 1]
```diff
@@ -30,9 +30,16 @@ impl CoreGroup {
             key_package_bundle.key_package.leaf_node().encryption_key(),
         )
         .ok_or(WelcomeError::NoMatchingEncryptionKey)?;
-        leaf_keypair
+
+        // Delete the [`KeyPackage`] and the corresponding private key from the
+        // key store, but only if it doesn't have a last resort extension.
```
Comment (kkohbrok) [inline openmls/src/group/core_group/new_from_welcome.rs:35]: Could you change the text here (and in the debug log entry below) to indicate that this is about the leaf encryption key pair and not the KeyPackage?

**Comment by josephlukefahr** [comment]
See 050d330 for the test.  Open to feedback/guidance on a more robust test procedure for this case.

**Comment by josephlukefahr** [comment]
See 4253a26 for the `cargo fmt` changes.

File: openmls/src/group/core_group/new_from_welcome.rs (hunk 1 above)
Comment (kkohbrok) [reply openmls/src/group/core_group/new_from_welcome.rs:35]: Thanks!

**Review by kkohbrok — APPROVED** [review]
Thanks for adding the test and making the requested changes! This looks good to me, but clippy has a few complaints. Once you sort those out we can get this merged.

**Review by kkohbrok — CHANGES_REQUESTED** [review]
Sorry, one last thing: Could you add an entry to the changelog indicating that this bug was fixed? You can find it in CHANGELOG.md.

**Review by kkohbrok — APPROVED** [review]
Excellent, thanks!
