### PR TITLE
Fix Typo and add GroupContextExtension example for Unknown Extensions

### LINKED ISSUE #1686: Add example showing how an application can insert and access GroupContextExternsions

### PR DESCRIPTION
**Pull request by keks**
This PR fixes typos in the name of a commit builder function, adds an getter for unknown extensions in `Extensions` and adds a test case that serves as an example for how to access custom group context extensions, both when joining from a welcome or when processing a commit.

Fixes #1686

### CODE REVIEW

File: openmls/src/extensions/mod.rs [hunk 1]
```diff
@@ -420,6 +420,19 @@ impl Extensions {
                 _ => None,
             })
     }
+
+    /// Get a reference to the [`UnknownExtension`] with the given type id, if there is any.
+    pub fn unknown(&self, extension_type_id: u16) -> Option<&UnknownExtension> {
```
Comment (franziskuskiefer) [inline openmls/src/extensions/mod.rs:425]: This is a new public function that should go into the changelog.

**Review by franziskuskiefer — CHANGES_REQUESTED** [review]
lgtm with one nit.

Looks like we also didn't add the commit builder to the changelog. Let's do that in a follow-up.

**Review by franziskuskiefer — APPROVED** [review]
Thanks
